### ISSUE TITLE
unsatisfied trait bound

### ISSUE THREAD

**Issue by iEricKoh** [http-rs/surf#79] opened 2019-10-14 07:15 UTC
I am currently using `surf v1.0.2` with `rustc 1.40.0-nightly (c27f7568b 2019-10-13)`.

Here's the error when I trying to run the example on the README.

```
error[E0277]: the trait bound `std::io::Empty: futures_io::if_std::AsyncRead` is not satisfied
  --> /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-1.0.2/src/http_client/mod.rs:64:21
   |
64 |             reader: Box::new(std::io::empty()),
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `futures_io::if_std::AsyncRead` is not implemented for `std::io::Empty`
   |
   = note: required for the cast to the object type `dyn futures_io::if_std::AsyncRead + std::marker::Send + std::marker::Unpin`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `surf`.
```

**Comment by xmclark** [comment] 2019-10-15 05:00
Came here to report this. I am able to reproduce it with a minimal reproducible example:

toolchain:
beta-x86_64-pc-windows-gnu

```toml
[package]
name = "basic-example-rustasync"
version = "0.1.0"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
runtime = "0.3.0-alpha.7"
surf = "1.0.2"
```

```
#[runtime::main]
async fn main() {
}
```

**Comment by taiki-e** [comment] 2019-10-15 10:00
This is a duplicate of #73 - It has already been fixed in master, but a new version has not yet been released. (cc @yoshuawuyts)

**Comment by yoshuawuyts** [comment] 2019-11-20 00:24
This should have been fixed in the latest release. Going to go ahead and close this. Apologies for the delay, and thanks for reporting!

**Closed by yoshuawuyts** 2019-11-20 00:24 UTC
